apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: openshift-monitoring
  name: prometheus-operator-uwm-kube-rbac-proxy-config
  namespace: openshift-user-workload-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "static":
      - "path": "/metrics"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
type: Opaque
