apiVersion: v1
data:
  metadata-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "Metadata"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "Metadata"
  none-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "None"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "None"
  request-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "Request"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "Request"
  requestresponse-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "RequestResponse"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "RequestResponse"
kind: ConfigMap
metadata:
  name: prometheus-adapter-audit-profiles
  namespace: openshift-monitoring
