apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-querier
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.23.1
  name: thanos-querier-oauth-htpasswd
  namespace: openshift-monitoring
type: Opaque
