apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-ruler
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.23.1
  name: thanos-ruler
  namespace: openshift-user-workload-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: web
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: server-name-replaced-at-runtime
  selector:
    matchLabels:
      app.kubernetes.io/component: rule-evaluation-engine
      app.kubernetes.io/instance: thanos-ruler
      app.kubernetes.io/name: thanos-rule
      app.kubernetes.io/part-of: openshift-monitoring
